- id: rubocop
  name: Check Ruby style with rubocop
  description: Enforce Ruby style guide with rubocop
  entry: bin/rubocop-wrapper.sh
  language: script
  pass_filenames: true
  types: ['ruby']
  verbose: true
- id: rspec
  name: Unit test Ruby code with rspec
  description: Run rspec in changed paths with spec directories
  entry: bin/rspec-wrapper.rb
  language: script
  pass_filenames: true
  types: ['ruby']
  verbose: true
- id: cookstyle
  name: Enforce Chef style guide with cookstyle
  description: Enforce Chef style guide with cookstyle
  entry: bin/cookstyle-wrapper.rb
  language: script
  pass_filenames: true
  types: ['ruby']
  files: .*
  args:
    - -a
    - -D
  verbose: true
  require_serial: true
- id: foodcritic
  name: Enforce Chef style guide with foodcritic
  description: Enforce Chef style guide with foodcritic
  entry: bin/foodcritic-wrapper.rb
  language: script
  pass_filenames: true
  types: ['ruby']
  files: >
    (?x)^(
        (.*/)?(recipes|attributes|resources|providers)/.*\.rb|
        (.*/)?metadata\.rb
    )$
  exclude: .*/test/.*\.rb$
  args:
    - --epic-fail any
  verbose: true
  require_serial: true
